### PR TITLE
WIP: Resolve merge conflicts main and Data2.0, fix requirements and add test functions

### PR DESCRIPTION
**Pull request by l-kotzur**
I want to use the database in a production system. Further, I wanted to add and benchmark another performance model.

Therefore, I am writing some test functions that guarantee reproducibility and interface compatibility for new releases.

Further, I fixed some merge conflicts between the two above mentioned branches.

### CODE REVIEW

**Review by xihaui — COMMENTED** [review]
Thanks for your work on the hplib. I will add some good ideas like the test functions and the relative paths to Data2.0. 
From there i will make a new Merge request because there are functions in hplib.py which are not used anymore.

**Comment by l-kotzur** [comment]
Thank you for this library! 

I can delete the old functions too if you want. Are they in the hplib.py itself? 

I was not able to merge main and Data2.0 without these obstacles. I tried to resolve the majority of the merge conflicts but unfortunately, I did not cover all :/

**Comment by xihaui** [comment]
Yeah got into the same struggles. 
It is definetly the class `Same_Built()` (line 714) and the function `load_all_heat_pumps` (line 26)  in hplib.py.
I think we can merge it and do it afterward. As you like. @ttjaden needs to merge. It seems like I don`t have writing access.

**Review by ttjaden — APPROVED** [review]
I looked roughly over it. Small details can be changed after merge is done

**Pull request merged**
